# Generated by Django 3.2.9 on 2021-11-29 15:19

from django.db import migrations, models
#import website.validators


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='video/%y', validators=[website.validators.file_size]),
        ),
    ]
