# Generated by Django 3.2.7 on 2021-10-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='postwiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postwiki', models.CharField(max_length=100000)),
            ],
        ),
    ]
