# Generated by Django 3.2.7 on 2021-10-04 22:06

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postwiki',
            name='title',
            field=models.CharField(default=builtins.print, max_length=100),
            preserve_default=False,
        ),
    ]
